---
# yamllint disable rule:line-length
name: Outdated package checker
description: check for outdated nuget and npm packages

inputs:
  # use dotnet outdated
  use-dotnet-outdated:
    description: Use dotnet outdated
    required: false
    default: 'false'

  # required for dotnet outdated
  dotnet-solution-path:
    description: Path of the solution file
    required: false
    default: ''

  # use npm outdated
  use-npm-outdated:
    description: Use npm outdated
    required: false
    default: 'false'

  # required for npm outdated
  npm-project-directory:
    description: Path of the npm project directory
    required: false
    default: ''

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    # Validate action inputs
    - name: Validate action inputs
      shell: bash
      run: |
        echo "use-dotnet-outdated:   ${{ inputs.use-dotnet-outdated }}"
        echo "dotnet-solution-path:  ${{ inputs.dotnet-solution-path }}"
        echo "use-npm-outdated:      ${{ inputs.use-npm-outdated }}"
        echo "npm-project-directory: ${{ inputs.npm-project-directory }}"

        if ([[ "${{ inputs.use-dotnet-outdated }}" == 'true' ]] && [[ -z "${{ inputs.dotnet-solution-path }}" ]]); then
          echo "dotnet-solution-path is empty"; error=true;
        fi

        if ([[ "${{ inputs.use-npm-outdated }}" == 'true' ]] && [[ -z "${{ inputs.npm-project-directory }}" ]]); then
          echo "npm-project-directory is empty"; error=true;
        fi

        if [ -n "${error}" ]; then
          echo "One or more inputs are invalid"
          exit 1
        fi

    # NPM outdated
    - name: NPM install
      if: ${{ inputs.use-npm-outdated == 'true' }}
      working-directory: ${{ inputs.npm-project-directory }}
      shell: bash
      run: npm install

    - name: NPM update check
      if: ${{ inputs.use-npm-outdated == 'true' }}
      uses: MeilCli/npm-update-check-action@v4 
      id: npm-outdated-check
      with:
        execute_directories: ${{ inputs.npm-project-directory }}
        output_text_style: short

    - name: Create npm outdated comment
      if: ${{ inputs.use-npm-outdated == 'true' }}
      id: npm-outdated-comment
      working-directory: ${{ inputs.npm-project-directory }}
      shell: bash
      run: |
        if [[ "${{ steps.npm-outdated-check.outputs.has_npm_update }}" = "false" ]]; then
            printf "## No outdated npm packages found :rocket:" >> npm_outdated.md
            echo "NPM_SHOULD_FAIL=false" >> "$GITHUB_OUTPUT"
        else
            printf "${{ steps.npm-outdated-check.outputs.npm_update_text }}" >> npm_outdated.md
            echo ' ' | cat - npm_outdated.md > temp && mv temp npm_outdated.md
            echo '> Outdated npm packages found, update if possible. Run ```npm outdated``` in the terminal to view locally.' | cat - npm_outdated.md > temp && mv temp npm_outdated.md
            echo '> [!WARNING]' | cat - npm_outdated.md > temp && mv temp npm_outdated.md

            echo "NPM_SHOULD_FAIL=false" >> "$GITHUB_OUTPUT"
        fi

    - name: NPM outdated PR comment
      if: ${{ inputs.use-npm-outdated == 'true' }}
      uses: thollander/actions-comment-pull-request@v2
      with:
        filePath: "${{ inputs.npm-project-directory }}/npm_outdated.md"
        comment_tag: npm_outdated

    # Dotnet outdated
    - name: Restore packages
      if: ${{ inputs.use-dotnet-outdated == 'true' }}
      shell: bash
      run: dotnet restore ${{ inputs.dotnet-solution-path }}

    - name: Install dotnet outdated tool
      if: ${{ inputs.use-dotnet-outdated == 'true' }}
      shell: bash
      run: dotnet tool install --global dotnet-outdated-tool

    - name: Run outdated script
      if: ${{ inputs.use-dotnet-outdated == 'true' }}
      id: dotnet-outdated
      shell: bash
      run: |
        echo "dotnet outdated ${{ inputs.dotnet-solution-path }} -of Markdown -o outdated.md"

        OUTPUT=`dotnet outdated ${{ inputs.dotnet-solution-path }} -of Markdown -o outdated.md`
        echo "$OUTPUT"

        if [[ $OUTPUT =~ "No outdated dependencies" ]]; then
            printf "## No outdated nuget packages found :rocket:" >> outdated.md
            echo "SHOULD_FAIL=false" >> "$GITHUB_OUTPUT"
        elif [[ $OUTPUT =~ "Errors occurred" ]]; then
            printf "> Failure when checking for outdated nuget packages" >> outdated.md
            echo '> [!CAUTION]' | cat - outdated.md > temp && mv temp outdated.md
            echo "SHOULD_FAIL=true" >> "$GITHUB_OUTPUT"
        else
            echo '> Outdated nuget packages found, update if possible' | cat - outdated.md > temp && mv temp outdated.md
            echo '> [!WARNING]' | cat - outdated.md > temp && mv temp outdated.md
            echo "SHOULD_FAIL=false" >> "$GITHUB_OUTPUT"
        fi

    - name: Dotnet outdated PR comment
      if: ${{ inputs.use-dotnet-outdated == 'true' }}
      uses: thollander/actions-comment-pull-request@v2
      with:
        filePath: "outdated.md"
        comment_tag: outdated